#commands:
#  sayhello:
#    description: "A very simple command for demonstration purposes"
#    parameters:
#      to:
#        type: string
#        default: "Hello World"
#    steps:
#      - run: echo << parameters.to >>
#
#jobs:
#  build:
#    docker:
#      - image: "circleci/node:9.6.1"
#    steps:
#      - sayhello:
#          to: "Lev"

version: 2.1

orbs:
  ror: circleci/rails@volatile
  my-orb:
    executors:
      default:
        docker:
          - image: circleci/ruby:1.4.2
    commands:
      dospecialthings:
        steps:
          - run:
              echo: "We will now do special things"
    jobs:
      myjob:
        executor: default
        steps:
          - dospecialthings

workflows:
  main:
    - my-orb/myjob
