version: 2.1

orbs:
  my-orb:
    executors:
      default:
        docker:
          - image: circleci/ruby:1.4.2
    commands:
      dospecialthings:
        steps:
          - run: echo: "We will now do special things"
    jobs:
      myjob:
        executor: default
        steps:
          - dospecialthings

workflows:
  main:
    - my-orb/myjob
